export const data = [
  {
    id: 1,
    assignee: 'Deb Weatherhogg',
    subject: 'Physics',
    title: 'Sharon Rothman',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
    assigned_date: '29/08/2022',
    submission_date: '11/28/2022',
    status: 'done',
    isNew: false,
  },
  {
    id: 2,
    assignee: 'Olivia Steele',
    subject: 'Chemistry',
    assigned_date: '07/06/2022',
    submission_date: '3/5/2022',
    status: 'pending',
    isNew: true,
    title: 'Dareen Luggar',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 3,
    assignee: 'Rosita Cock',
    subject: 'Mathematics',
    assigned_date: '18/12/2021',
    submission_date: '12/14/2022',
    status: 'done',
    isNew: false,
    title: 'Hurleigh Roscoe',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 4,
    assignee: 'Morse Turvie',
    subject: 'Mathematics',
    assigned_date: '12/09/2022',
    submission_date: '12/14/2022',
    status: 'pending',
    isNew: true,
    title: 'Garreth Pinney',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 5,
    assignee: 'Agnella Marchment',
    subject: 'Geography',
    assigned_date: '10/09/2022',
    submission_date: '5/17/2022',
    status: 'pending',
    isNew: true,
    title: 'Ira Redwall',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 6,
    assignee: 'Mady Almack',
    subject: 'History',
    assigned_date: '15/01/2022',
    submission_date: '12/17/2021',
    status: 'done',
    isNew: false,
    title: 'Jorgan Carlisi',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 7,
    assignee: 'Garik Sartain',
    subject: 'Hindi',
    assigned_date: '21/03/2022',
    submission_date: '4/9/2022',
    status: 'late',
    isNew: false,
    title: 'Estele Kenaway',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 8,
    assignee: 'Skell Fleury',
    subject: 'Hindi',
    assigned_date: '17/09/2022',
    submission_date: '5/17/2022',
    status: 'late',
    isNew: true,
    title: 'Yvon Turbill',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 9,
    assignee: 'Iolanthe McLelland',
    subject: 'English',
    assigned_date: '06/02/2022',
    submission_date: '2/16/2022',
    status: 'done',
    isNew: false,
    title: 'Christophe Kollach',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 10,
    assignee: 'Godfry Hodcroft',
    subject: 'English',
    assigned_date: '05/05/2022',
    submission_date: '10/18/2022',
    status: 'pending',
    isNew: true,
    title: 'Luella Bilovus',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 11,
    assignee: 'Benedikt Nimmo',
    subject: 'Mathematics',
    assigned_date: '24/05/2022',
    submission_date: '1/7/2022',
    status: 'late',
    isNew: true,
    title: 'Rollo Heasley',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 12,
    assignee: 'Teresa Radmore',
    subject: 'Mathematics',
    assigned_date: '09/11/2022',
    submission_date: '12/5/2022',
    status: 'late',
    isNew: true,
    title: 'Lacey Abramzon',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 13,
    assignee: 'Wylie Axe',
    subject: 'Hsitory',
    assigned_date: '06/01/2022',
    submission_date: '10/1/2022',
    status: 'pending',
    isNew: true,
    title: 'Debbi MacParland',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 14,
    assignee: 'Josselyn Dudden',
    subject: 'History',
    assigned_date: '06/11/2022',
    submission_date: '6/24/2022',
    status: 'done',
    isNew: false,
    title: 'Emilio Hinken',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 15,
    assignee: 'Sisely Margerison',
    subject: 'History',
    assigned_date: '06/01/2022',
    submission_date: '5/10/2022',
    status: 'late',
    isNew: false,
    title: 'Daisy Mollene',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 16,
    assignee: 'Constance Milby',
    subject: 'Physics',
    assigned_date: '12/03/2022',
    submission_date: '4/13/2022',
    status: 'pending',
    isNew: true,
    title: 'Margret Ishak',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 17,
    assignee: 'Bevan Soeiro',
    subject: 'Physics',
    assigned_date: '02/04/2022',
    submission_date: '12/4/2022',
    status: 'late',
    isNew: true,
    title: 'Tarah Dalzell',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 18,
    assignee: "Alfie O'Hallagan",
    subject: 'Chemistry',
    assigned_date: '07/01/2022',
    submission_date: '10/8/2022',
    status: 'pending',
    isNew: true,
    title: 'Marianna Thominga',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 19,
    assignee: 'Barnaby Sertin',
    subject: 'Sanskrit',
    assigned_date: '07/09/2022',
    submission_date: '1/27/2022',
    status: 'done',
    isNew: false,
    title: 'Hirsch Goodfellowe',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
  {
    id: 20,
    assignee: 'Tripp Stairs',
    subject: 'English',
    assigned_date: '06/04/2022',
    submission_date: '12/20/2021',
    status: 'late',
    isNew: true,
    title: 'Alfonso Russell',
    assignment_file: 'https://files.eric.ed.gov/fulltext/ED491517.pdf',
  },
];
